### ISSUE TITLE
Support multiple fonts

### ISSUE THREAD

**Issue by aidistan** [aidistan/firefox-weixin-danmu#12]
Here is a list of the fonts to be supported:
- `:雅`：雅黑（默认）
- `:宋`：宋体
- `:思`：思源

**Comment by AngelaYing** [comment]
I arrived here~~

**Comment by AngelaYing** [comment]
Dies ist interessant. Kommen Sie trocken, junger Mann!!

**Comment by aidistan** [comment]
Do we really need this feature?

**Comment by aidistan** [comment]
感觉这个特性的需求不是很强，暂时冻结。
